# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180713_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='travel.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=15),
        ),
    ]
