# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='BreifContent',
            new_name='BriefContent',
        ),
    ]
